language: node_js
sudo: false
cache:
  directories:
  - node_modules
matrix:
  include:
  - node_js: '8.9'
  - node_js: '9.5'
    env: npm_config_coverage=1
addons:
  code_climate:
    repo_token:
      secure: APjRtr3gqPWFCjrq3qkaZ54AvscHGp0y4CitTKioNu5U9tywn0CBjjdz/5Nirptzci1y3+6mFFt6SfKXnitpgcRm6TBSU8fa3aCptgABBlHON6qARwSCggSDf4rc+12/ImGxNI/dy5DXbKcRfcdRj170Y8HxhLAH7R43KrOi1Fc=
after_success: |
  if [ -n "$npm_config_coverage" ]; then
    npm install -g codeclimate-test-reporter
    codeclimate-test-reporter < coverage/lcov.info
  fi
deploy:
  provider: npm
  email: me@samcday.com.au
  api_key:
    secure: ORS8eezs/Y/WfSK4U2sy5tTqpKtC/gdyp2r6TbssuUpgsIzdTa/KgH+gO3OugQarWSvG7KbxsWvRkkpl/4o68QJug0Tx5ZUncTNkcmyzjKhqg9rLfV+Y59xA4WJ8kri7XT2A2yvc6TBKpkONHIpJysBpmIsZqJHc5q/ItUSgjfU=
  on:
    tags: true
    repo: samcday/node-google-spreadsheets
    node: '9.5'
